### ISSUE TITLE
Set up a Spark test database with ODBC endpoint and configure tests to fail against it

### ISSUE THREAD

**Issue by sebbacon** [opensafely-core/cohort-extractor-v2#178]
We have tests that work against the MSSQL query engine. The next step is to get them to fail against a Spark/Databricks database, over ODBC.

* Locate a suitable docker image, probably through reference to Peter's existing work
* Attempt to understand how to make it provide an ODBC endpoint. This might be via a component called Thrift ([here's a breadcrumb](https://forums.databricks.com/questions/1464/how-to-configure-thrift-server-to-use-a-custom-spa.html) to follow)
* Configure the database for test access (connection credentials, authorisation to write tables for tests, pytest fixtures to start it up)
* Alter the current query engine to connect over ODBC (rather than TDS)
* Run the tests again

**Comment by evansd** [comment]
Just found this PR which might, when merged, provide an official way of starting a Thrift server using this docker image:
https://github.com/bitnami/bitnami-docker-spark/pull/42

Worth keeping an eye on but what we have works for now.

**Comment by sebbacon** [comment]
[You're right about the primary keys](https://github.com/dropbox/PyHive/blob/d6e7140d366cc37d01af0d8308e7739d090d73ef/pyhive/sqlalchemy_presto.py#L166-L168); I presume that means there's a bug in how PyHive creates tables.

**Comment by evansd** [comment]
### Parking Notes

Code in draft PR here https://github.com/opensafely-core/cohort-extractor-v2/pull/180

It turns out it is possible to get the SQLAlchemy ORM to create our fixtures inside Spark using pyhive.
This requires subclassing pyhive and applying some tweaks:
https://github.com/opensafely-core/cohort-extractor-v2/blob/e2bc271bcc54c198f39eae88bef02adda1377844/my_dialect.py

Also, Spark can't provide the auto-increment primary keys which the ORM expects (or provide any primary key support at all) but the ORM insists on having a primary key so I just told it that some fields were primary keys and that kept it quiet for now:
https://github.com/opensafely-core/cohort-extractor-v2/blob/e2bc271bcc54c198f39eae88bef02adda1377844/tests/lib/databricks_schema.py

The other changes I needed to make were replacing `SELECT * INTO #temptable FROM (...)` with `CREATE TEMPORARY VIEW temptable AS ...`. And replacing the session scoped `#codelist` tables with non-temporary tables that we DROP before recreating.

The failure at the moment is:
```
================================================================= FAILURES =================================================================
__________________________________________________ test_basic_databricks_study_definition __________________________________________________
Traceback (most recent call last):
  File "/home/dave/projects/ebmdatalab/cohort-extractor-v2/tests/backends/test_databricks.py", line 97, in test_basic_databricks_study_definition
    assert sorted(
AssertionError: assert [{'admitted': True,\n  'dob': '1950-08-20',\n  'patient_id': 10,\n  'prescribed_med': None},\n {'admitted': None,\n  'dob': '1955-07-17',\n  'patient_id': 15,\n  'prescribed_med': True}] == [{'admitted': True,\n  'dob': datetime.date(1950, 8, 20),\n  'patient_id': 10,\n  'prescribed_med': None},\n {'admitted': None,\n  'dob': datetime.date(1955, 7, 17),\n  'patient_id': 15,\n  'prescribed_med': True}]
  At index 0 diff: {'patient_id': 10, 'dob': '1950-08-20', 'prescribed_med': None, 'admitted': True} != {'patient_id': 10, 'dob': datetime.date(1950, 8, 20), 'prescribed_med': None, 'admitted': True}
  Full diff:
    [
     {'admitted': True,
  -   'dob': datetime.date(1950, 8, 20),
  +   'dob': '1950-08-20',
      'patient_id': 10,
      'prescribed_med': None},
     {'admitted': None,
  -   'dob': datetime.date(1955, 7, 17),
  +   'dob': '1955-07-17',
      'patient_id': 15,
      'prescribed_med': True},
    ]
```

**Comment by evansd** [comment]
Done, code now in #180
